// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Models;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20231110093610_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("src.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97c01"),
                            Nombre = "Actividades Pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97c02"),
                            Nombre = "Actividades Personales",
                            Peso = 40
                        });
                });

            modelBuilder.Entity("src.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97f01"),
                            CategoriaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97c01"),
                            FechaCreacion = new DateTime(2023, 11, 10, 5, 36, 10, 326, DateTimeKind.Local).AddTicks(2880),
                            Prioridad = 1,
                            Titulo = "Pago de servicios públicos"
                        },
                        new
                        {
                            TareaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97f02"),
                            CategoriaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97c01"),
                            FechaCreacion = new DateTime(2023, 11, 10, 5, 36, 10, 326, DateTimeKind.Local).AddTicks(2893),
                            Prioridad = 0,
                            Titulo = "Compra de productos"
                        },
                        new
                        {
                            TareaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97f03"),
                            CategoriaId = new Guid("3ca96d4d-5b31-4637-a9e6-752395e97c02"),
                            FechaCreacion = new DateTime(2023, 11, 10, 5, 36, 10, 326, DateTimeKind.Local).AddTicks(2896),
                            Prioridad = 1,
                            Titulo = "Terminar de ver series"
                        });
                });

            modelBuilder.Entity("src.Models.Tarea", b =>
                {
                    b.HasOne("src.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("src.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
